// 获取表格的数据
export const tableList = {
  "list": [
    {
      "key": 0,
      "disabled": true,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 0",
      "title": "一个任务名称 0",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 937,
      "status": 3,
      "updatedAt": "2017-06-30T16:00:00.000Z",
      "createdAt": "2017-06-30T16:00:00.000Z",
      "progress": 99
    },
    {
      "key": 3,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 3",
      "title": "一个任务名称 3",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 504,
      "status": 2,
      "updatedAt": "2017-07-01T16:00:00.000Z",
      "createdAt": "2017-07-01T16:00:00.000Z",
      "progress": 50
    },
    {
      "key": 4,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 4",
      "title": "一个任务名称 4",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 162,
      "status": 1,
      "updatedAt": "2017-07-02T16:00:00.000Z",
      "createdAt": "2017-07-02T16:00:00.000Z",
      "progress": 88
    },
    {
      "key": 5,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 5",
      "title": "一个任务名称 5",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 212,
      "status": 2,
      "updatedAt": "2017-07-02T16:00:00.000Z",
      "createdAt": "2017-07-02T16:00:00.000Z",
      "progress": 24
    },
    {
      "key": 6,
      "disabled": true,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 6",
      "title": "一个任务名称 6",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 243,
      "status": 3,
      "updatedAt": "2017-07-03T16:00:00.000Z",
      "createdAt": "2017-07-03T16:00:00.000Z",
      "progress": 69
    },
    {
      "key": 7,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 7",
      "title": "一个任务名称 7",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 893,
      "status": 0,
      "updatedAt": "2017-07-03T16:00:00.000Z",
      "createdAt": "2017-07-03T16:00:00.000Z",
      "progress": 20
    },
    {
      "key": 8,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 8",
      "title": "一个任务名称 8",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 609,
      "status": 2,
      "updatedAt": "2017-07-04T16:00:00.000Z",
      "createdAt": "2017-07-04T16:00:00.000Z",
      "progress": 8
    },
    {
      "key": 9,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 9",
      "title": "一个任务名称 9",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 459,
      "status": 1,
      "updatedAt": "2017-07-04T16:00:00.000Z",
      "createdAt": "2017-07-04T16:00:00.000Z",
      "progress": 9
    },
    {
      "key": 10,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 10",
      "title": "一个任务名称 10",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 339,
      "status": 0,
      "updatedAt": "2017-07-05T16:00:00.000Z",
      "createdAt": "2017-07-05T16:00:00.000Z",
      "progress": 78
    },
    {
      "key": 11,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 11",
      "title": "一个任务名称 11",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 470,
      "status": 3,
      "updatedAt": "2017-07-05T16:00:00.000Z",
      "createdAt": "2017-07-05T16:00:00.000Z",
      "progress": 83
    },
    {
      "key": 13,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 13",
      "title": "一个任务名称 13",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 739,
      "status": 3,
      "updatedAt": "2017-07-06T16:00:00.000Z",
      "createdAt": "2017-07-06T16:00:00.000Z",
      "progress": 67
    },
    {
      "key": 14,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 14",
      "title": "一个任务名称 14",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 360,
      "status": 2,
      "updatedAt": "2017-07-07T16:00:00.000Z",
      "createdAt": "2017-07-07T16:00:00.000Z",
      "progress": 9
    },
    {
      "key": 15,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 15",
      "title": "一个任务名称 15",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 645,
      "status": 2,
      "updatedAt": "2017-07-07T16:00:00.000Z",
      "createdAt": "2017-07-07T16:00:00.000Z",
      "progress": 30
    },
    {
      "key": 16,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 16",
      "title": "一个任务名称 16",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 92,
      "status": 0,
      "updatedAt": "2017-07-08T16:00:00.000Z",
      "createdAt": "2017-07-08T16:00:00.000Z",
      "progress": 9
    },
    {
      "key": 17,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 17",
      "title": "一个任务名称 17",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 82,
      "status": 1,
      "updatedAt": "2017-07-08T16:00:00.000Z",
      "createdAt": "2017-07-08T16:00:00.000Z",
      "progress": 52
    },
    {
      "key": 18,
      "disabled": true,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 18",
      "title": "一个任务名称 18",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 283,
      "status": 2,
      "updatedAt": "2017-07-10T00:00:00.000Z",
      "createdAt": "2017-07-10T00:00:00.000Z",
      "progress": 12
    },
    {
      "key": 19,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 19",
      "title": "一个任务名称 19",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 318,
      "status": 3,
      "updatedAt": "2017-07-10T00:00:00.000Z",
      "createdAt": "2017-07-10T00:00:00.000Z",
      "progress": 67
    },
    {
      "key": 20,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 20",
      "title": "一个任务名称 20",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 290,
      "status": 0,
      "updatedAt": "2017-07-11T00:00:00.000Z",
      "createdAt": "2017-07-11T00:00:00.000Z",
      "progress": 37
    },
    {
      "key": 21,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 21",
      "title": "一个任务名称 21",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 715,
      "status": 1,
      "updatedAt": "2017-07-11T00:00:00.000Z",
      "createdAt": "2017-07-11T00:00:00.000Z",
      "progress": 40
    },
    {
      "key": 22,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 22",
      "title": "一个任务名称 22",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 261,
      "status": 2,
      "updatedAt": "2017-07-12T00:00:00.000Z",
      "createdAt": "2017-07-12T00:00:00.000Z",
      "progress": 93
    },
    {
      "key": 23,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 23",
      "title": "一个任务名称 23",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 434,
      "status": 0,
      "updatedAt": "2017-07-12T00:00:00.000Z",
      "createdAt": "2017-07-12T00:00:00.000Z",
      "progress": 81
    },
    {
      "key": 24,
      "disabled": true,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 24",
      "title": "一个任务名称 24",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 349,
      "status": 2,
      "updatedAt": "2017-07-13T00:00:00.000Z",
      "createdAt": "2017-07-13T00:00:00.000Z",
      "progress": 47
    },
    {
      "key": 25,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 25",
      "title": "一个任务名称 25",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 950,
      "status": 1,
      "updatedAt": "2017-07-13T00:00:00.000Z",
      "createdAt": "2017-07-13T00:00:00.000Z",
      "progress": 99
    },
    {
      "key": 26,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 26",
      "title": "一个任务名称 26",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 386,
      "status": 0,
      "updatedAt": "2017-07-14T00:00:00.000Z",
      "createdAt": "2017-07-14T00:00:00.000Z",
      "progress": 26
    },
    {
      "key": 27,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 27",
      "title": "一个任务名称 27",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 45,
      "status": 2,
      "updatedAt": "2017-07-14T00:00:00.000Z",
      "createdAt": "2017-07-14T00:00:00.000Z",
      "progress": 5
    },
    {
      "key": 28,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 28",
      "title": "一个任务名称 28",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 958,
      "status": 1,
      "updatedAt": "2017-07-15T00:00:00.000Z",
      "createdAt": "2017-07-15T00:00:00.000Z",
      "progress": 93
    },
    {
      "key": 29,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 29",
      "title": "一个任务名称 29",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 14,
      "status": 0,
      "updatedAt": "2017-07-15T00:00:00.000Z",
      "createdAt": "2017-07-15T00:00:00.000Z",
      "progress": 10
    },
    {
      "key": 30,
      "disabled": true,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 30",
      "title": "一个任务名称 30",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 748,
      "status": 0,
      "updatedAt": "2017-07-16T00:00:00.000Z",
      "createdAt": "2017-07-16T00:00:00.000Z",
      "progress": 74
    },
    {
      "key": 31,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 31",
      "title": "一个任务名称 31",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 642,
      "status": 1,
      "updatedAt": "2017-07-16T00:00:00.000Z",
      "createdAt": "2017-07-16T00:00:00.000Z",
      "progress": 19
    },
    {
      "key": 32,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 32",
      "title": "一个任务名称 32",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 530,
      "status": 2,
      "updatedAt": "2017-07-17T00:00:00.000Z",
      "createdAt": "2017-07-17T00:00:00.000Z",
      "progress": 96
    },
    {
      "key": 33,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 33",
      "title": "一个任务名称 33",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 635,
      "status": 1,
      "updatedAt": "2017-07-17T00:00:00.000Z",
      "createdAt": "2017-07-17T00:00:00.000Z",
      "progress": 53
    },
    {
      "key": 34,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 34",
      "title": "一个任务名称 34",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 523,
      "status": 0,
      "updatedAt": "2017-07-18T00:00:00.000Z",
      "createdAt": "2017-07-18T00:00:00.000Z",
      "progress": 23
    },
    {
      "key": 35,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 35",
      "title": "一个任务名称 35",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 566,
      "status": 3,
      "updatedAt": "2017-07-18T00:00:00.000Z",
      "createdAt": "2017-07-18T00:00:00.000Z",
      "progress": 82
    },
    {
      "key": 36,
      "disabled": true,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 36",
      "title": "一个任务名称 36",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 888,
      "status": 0,
      "updatedAt": "2017-07-19T00:00:00.000Z",
      "createdAt": "2017-07-19T00:00:00.000Z",
      "progress": 99
    },
    {
      "key": 37,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 37",
      "title": "一个任务名称 37",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 371,
      "status": 2,
      "updatedAt": "2017-07-19T00:00:00.000Z",
      "createdAt": "2017-07-19T00:00:00.000Z",
      "progress": 94
    },
    {
      "key": 38,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 38",
      "title": "一个任务名称 38",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 799,
      "status": 1,
      "updatedAt": "2017-07-20T00:00:00.000Z",
      "createdAt": "2017-07-20T00:00:00.000Z",
      "progress": 58
    },
    {
      "key": 39,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 39",
      "title": "一个任务名称 39",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 667,
      "status": 1,
      "updatedAt": "2017-07-20T00:00:00.000Z",
      "createdAt": "2017-07-20T00:00:00.000Z",
      "progress": 43
    },
    {
      "key": 40,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 40",
      "title": "一个任务名称 40",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 370,
      "status": 0,
      "updatedAt": "2017-07-21T00:00:00.000Z",
      "createdAt": "2017-07-21T00:00:00.000Z",
      "progress": 99
    },
    {
      "key": 41,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 41",
      "title": "一个任务名称 41",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 398,
      "status": 0,
      "updatedAt": "2017-07-21T00:00:00.000Z",
      "createdAt": "2017-07-21T00:00:00.000Z",
      "progress": 36
    },
    {
      "key": 42,
      "disabled": true,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 42",
      "title": "一个任务名称 42",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 930,
      "status": 0,
      "updatedAt": "2017-07-22T00:00:00.000Z",
      "createdAt": "2017-07-22T00:00:00.000Z",
      "progress": 78
    },
    {
      "key": 43,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 43",
      "title": "一个任务名称 43",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 912,
      "status": 1,
      "updatedAt": "2017-07-22T00:00:00.000Z",
      "createdAt": "2017-07-22T00:00:00.000Z",
      "progress": 44
    },
    {
      "key": 44,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png",
      "no": "TradeCode 44",
      "title": "一个任务名称 44",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 581,
      "status": 1,
      "updatedAt": "2017-07-23T00:00:00.000Z",
      "createdAt": "2017-07-23T00:00:00.000Z",
      "progress": 14
    },
    {
      "key": 45,
      "disabled": false,
      "href": "https://ant.design",
      "avatar": "https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png",
      "no": "TradeCode 45",
      "title": "一个任务名称 45",
      "owner": "曲丽丽",
      "description": "这是一段描述",
      "callNo": 242,
      "status": 1,
      "updatedAt": "2017-07-23T00:00:00.000Z",
      "createdAt": "2017-07-23T00:00:00.000Z",
      "progress": 36
    }
  ],
  "pagination": {
    "total": 43,
    "pageSize": 10,
    "current": 1
  }
}
/**
 * 表头数据格式
 */
export const tableColumns = [
  {
    title: '规则编号',
    dataIndex: 'no',
  },
  {
    title: '描述',
    dataIndex: 'description',
  },
  {
    title: '服务调用次数',
    dataIndex: 'callNo',
    sorter: true,
    align: 'right'
  },
  {
    title: '状态',
    dataIndex: 'status',
    filters: [
      {
        text: status[0],
        value: 0,
      },
      {
        text: status[1],
        value: 1,
      },
      {
        text: status[2],
        value: 2,
      },
      {
        text: status[3],
        value: 3,
      },
    ],
  },
  {
    title: '更新时间',
    dataIndex: 'updatedAt',
    sorter: true,
  },
  {
    title: '操作',
    dataIndex:'operation',
  },
]
/**
 * 菜单数据格式
 */
/**
 * 获取菜单列表
 * 可以通过接口动态获取
 * name     -- 菜单名称
 * route    -- 路由(前面一定要有个斜杠来区分是否跟路径)
 * icon     -- 对应的菜单前的图标
 * children -- 有对应的子菜单
 * 
 */
export const getMenus = () => {
  return [
    {
      name: 'Dashboard', route: 'dashboard', icon: 'bars',
      children: [
        { name: '分析页', route: '/dashboard/dashboard1' },
        { name: '监控页', route: '/dashboard/dashboard2' },
        { name: '工作台', route: '/dashboard/dashboard3' },
      ]
    },
    { name: '列表页', route: '/list', icon: 'file-text' },
    { name: '图表页', route: '/chart', icon: 'dot-chart' },
    { name: '表单页', route: '/form', icon: 'exception' },
    { name: '异常', route: '/error', icon: 'question-circle-o' }
  ]
}